In [32]:
#MONDAY 30TH SEPTEMBER
####KSRTC-KERALA              1111

In [1]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re

def initialize_driver():
    driver = webdriver.Chrome()  #Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/ksrtc-kerala/?utm_source=rtchometile")
    time.sleep(5)  

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
             # Get seat availability if present, else set it to 0
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'

            
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
    
    try:
        for page in range(1, 3):  #change the range as necessary for pagination
            load_page(driver,"https://www.redbus.in/online-booking/ksrtc-kerala/?utm_source=rtchometile") 

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH, f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']") )
                    )
                
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df1 = pd.DataFrame(all_bus_details)

#convert the dataframe from df1
kerala_bus_df=df1

#save  a dataframe to csv also
kerala_bus_df.to_csv("ksrtc_bus_details.csv", index=False)

In [3]:
kerala_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 51,Swift Deluxe Non AC Air Bus (2+2),19:00,04:30,3.9,640,16
1,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 1585,Swift Deluxe Non AC Air Bus (2+2),20:40,06:10,3.5,640,10
2,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 1586,Swift Deluxe Non AC Air Bus (2+2),21:30,06:55,3.5,640,1
3,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 56,SWIFT-GARUDA A/C SEATER BUS,23:40,10:00,3.5,640,2
4,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,DA Transports,A/C Sleeper (2+1),21:45,06:55,4.0,640,17
...,...,...,...,...,...,...,...,...,...
502,Kozhikode to Aluva,https://www.redbus.in/bus-tickets/kozhikode-to...,Galaxy Tours,2+1 Air Suspension A/C Seater / Sleeper,21:45,01:45,2.8,288,33
503,Kozhikode to Aluva,https://www.redbus.in/bus-tickets/kozhikode-to...,Galaxy Tours,A/C Semi Sleeper (2+2),21:45,01:45,2.8,288,16
504,Kozhikode to Aluva,https://www.redbus.in/bus-tickets/kozhikode-to...,CGR Tranz,A/C Semi Sleeper (2+2),23:59,04:20,2.4,288,24
505,Kozhikode to Aluva,https://www.redbus.in/bus-tickets/kozhikode-to...,BLM Transports,A/C Sleeper (2+1),22:00,02:15,3.9,288,8
506,Kozhikode to Aluva,https://www.redbus.in/bus-tickets/kozhikode-to...,A1 Travels,Bharat Benz A/C Sleeper (2+1),23:30,02:45,3.3,288,16

In [35]:
#####KTCL###
#KADAMBA      22222

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re

def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/ktcl/?utm_source=rtchometile")
    time.sleep(5)  

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'

            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
    
    try:
        for page in range(1, 5):  # Change the range as necessary for pagination
            load_page(driver,"https://www.redbus.in/online-booking/ktcl/?utm_source=rtchometile")

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH,f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']") )
                    )
                
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df2 = pd.DataFrame(all_bus_details)

#convert the dataframe into df2
kadamba_bus_df=df2

#save  a dataframe to csv also
kadamba_bus_df.to_csv("ktcl_bus_details.csv", index=False)

In [5]:
kadamba_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Kadamba Transport Corporation Limited (KTCL) -...,Volvo AC Seater 2+2,20:00,06:20,4.6,1000,2
1,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Gogte Travels,A/C Sleeper (2+1),18:15,07:00,4.3,1000,4
2,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Ashray Amrutyog,A/C Sleeper (2+1),20:20,09:30,4.5,1000,3
3,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Gogte Anand Travels,Volvo Multi-Axle I-Shift A/C Sleeper (2+1),19:30,07:55,4.2,1000,3
4,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Atmaram Gobus,VE A/C Sleeper (2+1),18:30,07:30,4.7,1000,4
...,...,...,...,...,...,...,...,...,...
338,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,Sangitam Travels Tanzanite,A/C Sleeper (2+1),21:00,04:30,4.2,550,15
339,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,IntrCity SmartBus,AC Sleeper (2+1),18:30,02:35,5.0,550,5
340,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,IntrCity SmartBus,AC Sleeper (2+1),19:00,03:25,4.7,550,8
341,Goa to Shirdi,https://www.redbus.in/bus-tickets/goa-to-shirdi,PSR Travels Goa,A/C Sleeper (2+1),19:45,10:30,3.5,1399,9
342,Goa to Shirdi,https://www.redbus.in/bus-tickets/goa-to-shirdi,Humsafar Travels,Bharat Benz A/C Sleeper (2+1),19:00,11:00,2.3,1399,11

In [38]:
###rsrtc###
#33333

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re


def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/rsrtc/?utm_source=rtchometile")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
    

    try:
        for page in range(1, 6):  # Change the range as necessary for pagination
            load_page(driver,"https://www.redbus.in/online-booking/rsrtc/?utm_source=rtchometile")

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH, f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']") )
                    )
                
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df3 = pd.DataFrame(all_bus_details)

#convert the dataframe into df3
andhra_bus_df=df3

#save  a dataframe to csv also
andhra_bus_df.to_csv("rsrtc_bus_details.csv", index=False)

In [7]:
andhra_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...,RSRTC - 176394,Super Luxury Volvo AC Seater Pushback 2+2,20:00,23:45,4.0,460,34
1,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...,RSRTC - 189473,NON AC Seater / Sleeper 2+1,21:00,01:30,4.8,460,34
2,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...,RSRTC - 192299,Super Luxury Volvo AC Seater Pushback 2+2,23:00,02:45,3.7,460,10
3,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...,RSRTC - 189583,NON AC Seater / Sleeper 2+1,23:59,03:45,4.4,460,25
4,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jakhar Travels,NON A/C Seater/ Sleeper (2+1),18:10,23:15,3.9,460,40
...,...,...,...,...,...,...,...,...,...
579,Udaipur to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/udaipur-to-j...,Jain Parshwanath Travels,AC Sleeper (2+1),22:06,06:01,2.6,527,24
580,Udaipur to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/udaipur-to-j...,Kalpana Travels Pvt. Ltd.,A/C Seater / Sleeper (2+1),22:00,06:15,2.4,527,28
581,Udaipur to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/udaipur-to-j...,Rishabh Travels Ajay Raj,Bharat Benz A/C Seater /Sleeper (2+1),21:55,05:05,2.2,527,28
582,Udaipur to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/udaipur-to-j...,Raj travels Jhunjhunu,A/C Seater / Sleeper (2+1),18:20,02:00,2.4,527,32
583,Udaipur to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/udaipur-to-j...,Rishabh Travels-Neeraj,Bharat Benz A/C Seater /Sleeper (2+1),18:30,03:00,2.7,527,31

In [41]:
###HRTC###    444

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re


def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/hrtc/?utm_source=rtchometile")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
    

    try:
        for page in range(1, 5):  # Change the range as necessary for pagination

            load_page(driver, "https://www.redbus.in/online-booking/hrtc/?utm_source=rtchometile")

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH,f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']") )
                )
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df4 = pd.DataFrame(all_bus_details)

#convert the dataframe into df4
hrtc_bus_df=df4

#save  a dataframe to csv also
hrtc_bus_df.to_csv("hrtc_bus_details.csv", index=False)

In [9]:
hrtc_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 93,Himsuta AC Seater Volvo/Scania 2+2,19:35,04:50,4.5,912,10
1,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 301,Ordinary 3+2 Non AC Seater,19:43,05:30,4.7,912,24
2,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 591,A/C Executive (2+3),21:00,07:20,3.2,912,37
3,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 8,Himsuta AC Seater Volvo/Scania 2+2,21:02,06:30,4.4,912,4
4,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,HRTC - 570,Ordinary 3+2 Non AC Seater,21:25,06:45,3.2,912,32
...,...,...,...,...,...,...,...,...,...
544,Ghumarwin to Delhi,https://www.redbus.in/bus-tickets/ghumarwin-to...,Bedi Travels,Volvo A/C Semi Sleeper (2+2),23:15,06:30,4.9,488,2
545,Ghumarwin to Delhi,https://www.redbus.in/bus-tickets/ghumarwin-to...,Ram Dalal Holidays,Volvo A/C Semi Sleeper (2+2),23:30,06:40,4.4,488,2
546,Manali to Shimla,https://www.redbus.in/bus-tickets/manali-to-sh...,HRTC - 155,Himsuta AC Seater Volvo/Scania 2+2,21:00,06:10,3.9,963,15
547,Manali to Shimla,https://www.redbus.in/bus-tickets/manali-to-sh...,HRTC - 718,Ordinary 3+2 Non AC Seater,21:30,06:35,4.1,963,27
548,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...,HRTC - 6639,A/C Executive (2+3),20:45,03:30,3.8,430,46

In [44]:
###JKSRTC###
#JAMMU-KASHMIR    5555

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re


def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/jksrtc")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()


    try:
        for page in range(1,6):  # Change the range as necessary for pagination

            load_page(driver, "https://www.redbus.in/online-booking/jksrtc")

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH, f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']") )
				)
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df5 = pd.DataFrame(all_bus_details)

#create a dataframe jksrtc
jksrtc_bus_df=df5

#save  a dataframe to csv also
jksrtc_bus_df.to_csv("jksrtc_bus_details.csv", index=False)  # Save without the index column

In [11]:
jksrtc_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Delhi to Srinagar,https://www.redbus.in/bus-tickets/delhi-to-sri...,Zingbus Plus,Bharat Benz A/C Seater /Sleeper (2+1),20:00,15:20,3.9,2062,1
1,Jammu (j and k) to Katra (jammu and kashmir),https://www.redbus.in/bus-tickets/jammu-to-katra,Bhawani Travels,A/C Seater / Sleeper (2+2),19:50,21:30,3.8,400,0
2,Jammu (j and k) to Katra (jammu and kashmir),https://www.redbus.in/bus-tickets/jammu-to-katra,Bhawani Travels,A/C Seater / Sleeper (2+2),20:00,21:45,3.8,400,0
3,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,FlixBus,Bharat Benz A/C Sleeper (2+1),18:30,20:00,4.1,88.39,32
4,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,Zingbus Plus,Bharat Benz A/C Seater /Sleeper (2+1),18:45,20:10,4.5,88.39,0
5,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,City Land Travels,A/C Sleeper (2+1),19:00,20:30,3.5,88.39,0
6,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,SHRI KRISHNA TRAVELS (JAI SHREE GANESH YATRA CO.),VE A/C Seater / Sleeper (2+1),19:30,20:30,3.7,88.39,0
7,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,KN Nehra Travels,A/C Seater / Sleeper (2+1),19:45,21:15,3.0,88.39,0
8,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,Zingbus Plus,A/C Sleeper (2+1),19:50,21:20,4.5,88.39,0
9,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,FlixBus,Bharat Benz A/C Sleeper (2+1),21:00,22:25,4.1,88.39,0
10,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,Namdev Travels,NON A/C Seater (2+2),18:30,20:30,2.5,88.39,0
11,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,Perfect Holiday,A/C Seater / Sleeper (2+2),21:10,22:55,2.1,88.39,0
12,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,Royal Golden,A/C Seater / Sleeper (2+2),23:00,00:00,4.0,88.39,0
13,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,VGO BUS,A/C Seater/Sleeper (2+1),18:30,19:30,3.7,88.39,0
14,Katra (jammu and kashmir) to Jammu (j and k),https://www.redbus.in/bus-tickets/katra-to-jammu,SHRI KRISHNA TRAVELS (JAI SHREE GANESH YATRA CO.),A/C Sleeper (2+2),20:00,21:00,0,88.39,0

In [47]:
###upsrtc###
    #6666

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re

def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/uttar-pradesh-state-road-transport-corporation-upsrtc/?utm_source=rtchometile")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
   

    try:
        for page in range(1,6):  # Change the range as necessary for pagination

            load_page(driver,"https://www.redbus.in/online-booking/uttar-pradesh-state-road-transport-corporation-upsrtc/?utm_source=rtchometile" )

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH,f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']") )
                )
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df6 = pd.DataFrame(all_bus_details)

#create a dataframe upsrtc
upsrtc_bus_df=df6

#save  a dataframe to csv also
upsrtc_bus_df.to_csv("upsrtc_bus_details.csv", index=False)  # Save without the index column

In [13]:
upsrtc_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - HDD0031,Ordinary Non AC Seater 2+3,19:45,03:10,3.3,495,52
1,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - KSB0089,Shatabdi AC Seater 2+2,19:46,01:31,3.3,495,37
2,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - HDD0105,Rajdhani Non AC Seater 2+3,20:00,01:41,3.3,495,51
3,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - LKM0400,Shatabdi AC Seater 2+2,20:02,01:30,3.3,495,37
4,Delhi to Bareilly (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - AWD0240,Janrath AC Seater 2+3,20:02,02:15,3.2,495,45
...,...,...,...,...,...,...,...,...,...
984,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - STD0072,Janrath AC Seater 2+2,22:40,05:45,2.5,567,32
985,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - LKM0401,Shatabdi AC Seater 2+2,23:15,06:14,3.3,567,34
986,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - KSB0221,Shatabdi AC Seater 2+2,23:30,06:00,3.3,567,37
987,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,UPSRTC - GND0100,Ordinary Non AC Seater 2+3,23:55,08:00,3.3,567,52
988,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...,RS YADAV SMART BUS,Bharat Benz A/C Seater /Sleeper (2+1),22:45,05:55,4.8,567,15

In [50]:
###ASTC###
#ASSAM     7777

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re


def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/astc/?utm_source=rtchometile")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
   

    try:
       for page in range(1,6):  # Change the range as necessary for pagination

          load_page(driver, "https://www.redbus.in/online-booking/astc/?utm_source=rtchometile")

          if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH,f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']") 
                ))
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

          all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

          for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df7 = pd.DataFrame(all_bus_details)

#create a dataframe astc
astc_bus_df = df7

#save  a dataframe to csv also
astc_bus_df.to_csv("astc_bus_details.csv", index=False)

In [15]:
astc_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),21:15,03:00,3.6,450,17
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),21:45,03:15,3.5,450,22
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,DESTINY TRAVELS,NON A/C Seater (2+1),22:15,03:45,2.2,450,28
3,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,DESTINY TRAVELS,NON A/C Seater (2+1),23:00,04:15,2.2,450,27
4,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Yatra Travels,NON AC Seater/ Sleeper (2+1),18:45,23:00,3.4,375,29
5,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Yatra Travels,NON A/C Seater/ Sleeper (2+1),19:30,00:30,3.4,375,25
6,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Yatra Travels,A/C Seater / Sleeper (2+1),20:00,01:30,3.4,375,24
7,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Pranjit Travels (Under ASTC),NON A/C Seater (2+1),20:15,00:30,3.0,375,24
8,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Yatra Travels,NON AC Seater/ Sleeper (2+1),20:30,01:00,4.3,375,27
9,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Pranjit Travels (Under ASTC),A/C Seater / Sleeper (2+1),20:45,02:30,3.0,375,26
10,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Pranjit Travels (Under ASTC),Non AC Seater (2+1),21:15,01:45,3.0,375,24
11,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Pranjit Travels (Under ASTC),NON A/C Seater (2+1),21:45,02:00,3.0,375,23
12,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Yatra Travels,NON A/C Seater (2+1),18:45,23:30,2.9,375,13
13,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),20:00,01:15,2.8,375,17
14,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Himalayan Travels,NON AC Seater / Sleeper 2+1,20:30,02:30,1.7,375,22
15,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,KIRAN TRAVELS,A/C Seater (2+1),20:40,00:30,2.1,375,3
16,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Pranjit Travels (Under ASTC),Bharat Benz A/C Seater (2+1),21:30,02:30,2.5,375,0
17,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...,Zainab Travels (Under ASTC),A/C Seater (2+1),20:30,01:30,3.5,375,0
18,Guwahati to Nagaon (Assam),https://www.redbus.in/bus-tickets/guwahati-to-...,Nishigandha(Divya Tours & Travels),A/C Seater (2+1),21:15,23:50,0,550,0
19,Dhubri to Guwahati,https://www.redbus.in/bus-tickets/dhubri-to-gu...,MAA MONOSHA TRAVELS,NON A/C Seater (2+1),20:00,03:30,3.3,347,32
20,Dhubri to Guwahati,https://www.redbus.in/bus-tickets/dhubri-to-gu...,Yatra,Non AC Seater (2+2),20:15,03:30,2.3,347,40
21,Jorhat to North Lakhimpur,https://www.redbus.in/bus-tickets/jorhat-to-no...,Priyanka,Non AC Seater (2+1),19:00,05:30,3.1,600,17
22,Tezpur to Dibrugarh,https://www.redbus.in/bus-tickets/tezpur-to-di...,SANJEEBANI TRAVELS,Non A/C Seater / Sleeper (2+1),21:30,05:00,3.9,700,3
23,Tezpur to Dibrugarh,https://www.redbus.in/bus-tickets/tezpur-to-di...,Neha Travels,NON A/C Seater (2+2),22:10,04:00,2.0,700,4
24,Tinsukia to Jorhat,https://www.redbus.in/bus-tickets/tinsukia-to-...,NETWORK TRAVELS,NON A/C Seater Push Back (2+1),19:00,00:30,4.8,500,17

In [53]:
#######  8888
##BSRTC###

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re


def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/bihar-state-road-transport-corporation-bsrtc/?utm_source=rtchometile")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
    

    try:
        for page in range(1,5):  # Change the range as necessary for pagination
            load_page(driver, "https://www.redbus.in/online-booking/bihar-state-road-transport-corporation-bsrtc/?utm_source=rtchometile")

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH,f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']")
                ))
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df8 = pd.DataFrame(all_bus_details)

#create a dataframe bsrtc
bsrtc_bus_df=df8

#save  a dataframe to csv also
bsrtc_bus_df.to_csv("bsrtc_bus_details.csv", index=False)

In [17]:
bsrtc_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Patna (Bihar) to Motihari,https://www.redbus.in/bus-tickets/patna-to-mot...,Bihar state road transport corporation (BSRTC)...,Non AC Seater (2+2),21:20,01:00,3.7,230,27
1,Patna (Bihar) to Motihari,https://www.redbus.in/bus-tickets/patna-to-mot...,Jai Hanuman Travels,A/C Seater / Sleeper (2+2),22:20,03:15,3.1,230,54
2,Patna (Bihar) to Motihari,https://www.redbus.in/bus-tickets/patna-to-mot...,Jai Hanuman Travels,A/C Seater / Sleeper (2+2),22:00,04:00,4.5,230,38
3,Patna (Bihar) to Motihari,https://www.redbus.in/bus-tickets/patna-to-mot...,Panwar Travels,A/C Seater / Sleeper (2+1),18:40,21:35,2.8,230,0
4,Patna (Bihar) to Motihari,https://www.redbus.in/bus-tickets/patna-to-mot...,Jai Mata Di Tour and Travels,A/C Seater / Sleeper (2+2),20:28,23:30,1.2,230,0
...,...,...,...,...,...,...,...,...,...
238,Patna (Bihar) to Ramgarh (Jharkhand),https://www.redbus.in/bus-tickets/patna-to-ram...,Pammi Travels,A/C Sleeper (2+1),20:30,04:30,3.6,466,36
239,Patna (Bihar) to Ramgarh (Jharkhand),https://www.redbus.in/bus-tickets/patna-to-ram...,Pappu Travels (yvts),A/C Seater/Sleeper (2+1),21:30,04:30,2.9,466,10
240,Patna (Bihar) to Ramgarh (Jharkhand),https://www.redbus.in/bus-tickets/patna-to-ram...,Tejas Maa Bhawani,AC Sleeper (2+1),21:30,04:30,2.0,466,2
241,Patna (Bihar) to Ramgarh (Jharkhand),https://www.redbus.in/bus-tickets/patna-to-ram...,Tejas Maa Bhawani,A/C Sleeper (2+1),21:30,05:00,2.0,466,2
242,Patna (Bihar) to Ramgarh (Jharkhand),https://www.redbus.in/bus-tickets/patna-to-ram...,Tejas Maa Bhawani,Non AC Seater (2+2),21:30,03:50,2.0,466,41

In [56]:
###nbstc###  99999

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re


def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/north-bengal-state-transport-corporation")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH, "//div[@class='seat-left m-top-30']")

        bus_details = []
        for i in range(len(bus_name_elements)):
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'
            bus_detail = {
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
    

    try:
        for page in range(1,5):  # Change the range as necessary for pagination
            load_page(driver,"https://www.redbus.in/online-booking/north-bengal-state-transport-corporation") 

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH,f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']")
                ))
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df9 = pd.DataFrame(all_bus_details)

#create a dataframe nbstc
nbstc_bus_df=df9

#save  a dataframe to csv also
nbstc_bus_df.to_csv("nbstc_bus_details.csv", index=False)

In [19]:
nbstc_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Kolkata to Siliguri,https://www.redbus.in/bus-tickets/kolkata-to-s...,NBSTC-KOL-RAI-SLG-19:30 - 176649,AC Seater (2+2),19:30,07:30,4.1,800,20
1,Kolkata to Siliguri,https://www.redbus.in/bus-tickets/kolkata-to-s...,SBSTC-KOLKATA - SILIGURI - VOLVO - 20:05 (BEL ...,Volvo AC Seater (2+2),20:05,09:05,3.9,800,49
2,Kolkata to Siliguri,https://www.redbus.in/bus-tickets/kolkata-to-s...,Express Line,Volvo 9600 A/C Seater/Sleeper (2+1),19:30,08:25,4.5,800,23
3,Kolkata to Siliguri,https://www.redbus.in/bus-tickets/kolkata-to-s...,AdLokenath Bus Service,Volvo Multi-Axle A/C Seater/Sleeper (2+1),20:00,08:00,4.4,800,36
4,Kolkata to Siliguri,https://www.redbus.in/bus-tickets/kolkata-to-s...,Shyamoli Paribahan Pvt Ltd,Volvo 9600 A/C Seater/Sleeper (2+1),21:00,10:00,4.3,800,22
...,...,...,...,...,...,...,...,...,...
248,Raiganj to Krishnanagar (West Bengal),https://www.redbus.in/bus-tickets/raiganj-to-k...,Aradhana Bus Service,NON A/C Seater / Sleeper (2+2),19:15,03:00,2.4,250,33
249,Raiganj to Krishnanagar (West Bengal),https://www.redbus.in/bus-tickets/raiganj-to-k...,Modern Travels,Bharat Benz A/C Seater /Sleeper (2+1),22:55,04:25,3.7,250,30
250,Raiganj to Krishnanagar (West Bengal),https://www.redbus.in/bus-tickets/raiganj-to-k...,Lokenath (Maa Tara),NON A/C Seater / Sleeper (2+2),19:45,03:20,2.7,250,8
251,Raiganj to Krishnanagar (West Bengal),https://www.redbus.in/bus-tickets/raiganj-to-k...,RAYAN,NON A/C Seater / Sleeper (2+2),22:00,05:00,2.3,250,59
252,Raiganj to Krishnanagar (West Bengal),https://www.redbus.in/bus-tickets/raiganj-to-k...,RAYAN,A/C Seater / Sleeper (2+1),21:15,04:00,2.3,250,55

In [59]:
###pepsu##
        #   10 10

In [ ]:
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re



def initialize_driver():
    driver = webdriver.Chrome()  # Make sure to import webdriver
    driver.maximize_window()
    return driver

def load_page(driver, url):
    driver.get("https://www.redbus.in/online-booking/pepsu/?utm_source=rtchometile")
    time.sleep(5)  # Allow the page to load completely

def scrape_bus_routes(driver):
    route_elements = driver.find_elements(By.CLASS_NAME, 'route')
    bus_routes_link = [route.get_attribute('href') for route in route_elements]
    bus_routes_name = [route.text for route in route_elements]
    return bus_routes_link, bus_routes_name

def scrape_bus_details(driver, url, route_name):
    try:
        driver.get(url)
        time.sleep(5)

        view_buses_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "button"))
        )
        driver.execute_script("arguments[0].scrollIntoView();", view_buses_button)
        driver.execute_script("arguments[0].click();", view_buses_button)
        time.sleep(5)

        # Scroll to the bottom of the page
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(5)

        # Locate bus details
        bus_name_elements = driver.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
        bus_type_elements = driver.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
        departing_time_elements = driver.find_elements(By.XPATH, "//div[@class='dp-time f-19 d-color f-bold']")
        #duration_elements = driver.find_elements(By.XPATH, "//div[@class='dur l-color lh-24']")
        arrival_elements = driver.find_elements(By.XPATH, "//div[@class='bp-time f-19 d-color disp-Inline']")
        star_rating_elements = driver.find_elements(By.XPATH, "//div[@class='rating-sec lh-24']")
        fare_element = driver.find_element(By.CSS_SELECTOR, "span.f-bold.f-19")
        seat_availability_elements = driver.find_elements(By.XPATH,'//div[@class="seat-left m-top-30"]')
        
        





        bus_details = []
        for i in range(len(bus_name_elements)):
             # Get seat availability if present, else set it to 0
            if i < len(seat_availability_elements):
                seat_text = seat_availability_elements[i].text
            else:
                seat_text = '0'  # Default to '0' if no seat availability element found

            
            # Extract numeric part using regex
            seat_number = re.search(r'\d+', seat_text)
            seat_number = seat_number.group() if seat_number else '0'

            bus_detail = {
        
            
                "Route_Name": route_name,
                "Route_Link": url,
                "Bus_Name": bus_name_elements[i].text,
                "Bus_Type": bus_type_elements[i].text,
                "Departing_Time": departing_time_elements[i].text,
                "Arrival_Time": arrival_elements[i].text,
                "Star_Rating": star_rating_elements[i].text if i < len(star_rating_elements) else '0',
                "Price": fare_element.text,
                "Seat_Availability": seat_number
            }
            bus_details.append(bus_detail)

        return bus_details

    except Exception as e:
        print(f"Error occurred while scraping bus details for {url}: {str(e)}")
        return []


def scrape_all_pages():
    all_bus_details = []
    driver = initialize_driver()
    

    try:
        for page in range(1,5):  # Change the range as necessary for pagination
            load_page(driver,("https://www.redbus.in/online-booking/pepsu/?utm_source=rtchometile"))

            if page > 1:
                pagination_tab = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.XPATH,f"//div[contains(@class,'DC_117_pageTabs')][text()='{page}']")
                ))
                driver.execute_script("arguments[0].scrollIntoView();", pagination_tab)
                driver.execute_script("arguments[0].click();", pagination_tab)
                time.sleep(5)

            all_bus_routes_link, all_bus_routes_name = scrape_bus_routes(driver)

            for link, name in zip(all_bus_routes_link, all_bus_routes_name):
                bus_details = scrape_bus_details(driver, link, name)
                if bus_details:
                    all_bus_details.extend(bus_details)

    except Exception as e:
        print(f"Error occurred while accessing page {page}: {str(e)}")
    
    finally:
        driver.quit()  # Ensure the driver is closed after scraping

    return all_bus_details

# Main execution
all_bus_details = scrape_all_pages()

# Convert the list of dictionaries to a DataFrame
df10 = pd.DataFrame(all_bus_details)

#create a dataframe pepsu
pepsu_bus_df=df10

#save  a dataframe to csv also
pepsu_bus_df.to_csv("pepsu_bus_details.csv", index=False)

In [21]:
pepsu_bus_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Arrival_Time,Star_Rating,Price,Seat_Availability
0,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...,Indo Canadian Transport Company,Mercedes A/C Semi Sleeper (2+2),23:30,06:30,4.6,3300,48
1,Ludhiana to Delhi,https://www.redbus.in/bus-tickets/ludhiana-to-...,PEPSU (Punjab) - 67128,Volvo AC Seater (2+2),20:50,02:49,3.9,873,33
2,Ludhiana to Delhi,https://www.redbus.in/bus-tickets/ludhiana-to-...,PEPSU (Punjab) - 67128,Volvo AC Seater (2+2),20:50,04:50,3.2,873,34
3,Ludhiana to Delhi,https://www.redbus.in/bus-tickets/ludhiana-to-...,PEPSU (Punjab) - 67164,Volvo AC Seater (2+2),21:50,04:50,4.3,873,28
4,Ludhiana to Delhi,https://www.redbus.in/bus-tickets/ludhiana-to-...,PEPSU (Punjab) - 67164,Volvo AC Seater (2+2),21:50,05:50,4.8,873,28
...,...,...,...,...,...,...,...,...,...
526,Amritsar to Delhi Airport,https://www.redbus.in/bus-tickets/amritsar-to-...,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),21:45,06:45,4.3,700,26
527,Amritsar to Delhi Airport,https://www.redbus.in/bus-tickets/amritsar-to-...,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),21:30,06:10,4.3,700,15
528,Amritsar to Delhi Airport,https://www.redbus.in/bus-tickets/amritsar-to-...,ADTC tour and Travels,Volvo Multi-Axle I-Shift B11R Semi Sleeper (2+2),21:20,05:10,4.2,700,23
529,Delhi Airport to Kapurthala,https://www.redbus.in/bus-tickets/delhi-airpor...,PEPSU (Punjab) - 67064,Volvo AC Seater (2+2),23:58,09:58,3.7,1226,37
530,Amritsar to Patiala,https://www.redbus.in/bus-tickets/amritsar-to-...,GK Travels,Bharat Benz A/C Seater /Sleeper (2+1),21:00,01:30,3.7,759,17

In [22]:
import pandas as pd

# Assume df1, df2, ..., df10 are your existing DataFrames representing the bus data.
# If you have these in variables or a list, you can combine them as follows:

# List of DataFrames (assuming df1, df2, ..., df10 are defined)
df_list = [kerala_bus_df, kadamba_bus_df, andhra_bus_df, hrtc_bus_df, jksrtc_bus_df, upsrtc_bus_df,astc_bus_df,bsrtc_bus_df,nbstc_bus_df , pepsu_bus_df]

# Combine all DataFrames into a single DataFrame
combined_df = pd.concat(df_list, ignore_index=True)

In [63]:
import pandas as pd
import psycopg2

# Assuming df is your DataFrame

# Connect to PostgreSQL
con = psycopg2.connect(
    database="homedb",
    user="postgres",
    password="mukisam290",
    host="localhost",  # e.g., 'localhost'
    port="5432"        # Default PostgreSQL port
)

cursor = con.cursor()

# Create table if it doesn't exist
create_table_query = """
CREATE TABLE IF NOT EXISTS redbus_bus_details (
    id SERIAL PRIMARY KEY,
    Route_Name VARCHAR(100),
    Route_Links VARCHAR(180),
    Busname VARCHAR(100),
    Bustype VARCHAR(80),
    departing_time TIME,
    reaching_time TIME,
    star_rating DECIMAL(2,1),
    price VARCHAR(80),
    seats_available INT
);
"""

# Execute the CREATE TABLE query
cursor.execute(create_table_query)
con.commit()

# Prepare the insert query
insert_query = """
INSERT INTO redbus_bus_details(
    Route_Name, Route_Links,Busname, Bustype, departing_time, reaching_time, 
    star_rating, price, seats_available
) VALUES (%s, %s, %s, %s, %s, %s, %s,%s,%s);
"""

# Convert DataFrame to a list of tuples
Redbus_details10 = combined_df.values.tolist()

# Insert data into the table
for row in Redbus_details10:
    cursor.execute(insert_query, row)

# Commit the changes
con.commit()

# Close the cursor and connection
cursor.close()
con.close()

print("Data inserted successfully!")

Data inserted successfully!

In [68]:
import pandas as pd
from sqlalchemy import create_engine



# connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into a csv format

data = pd.read_csv('astc_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

198

In [69]:
import pandas as pd
from sqlalchemy import create_engine



#  connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"



# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into csv format

data = pd.read_csv('bsrtc_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

346

In [70]:
import pandas as pd
from sqlalchemy import create_engine




# connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"



# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# give data into a csv format

data = pd.read_csv('hrtc_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

481

In [71]:
import pandas as pd
from sqlalchemy import create_engine



# connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into csv format

data = pd.read_csv('jksrtc_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

96

In [72]:
import pandas as pd
from sqlalchemy import create_engine



#  connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into csv format

data = pd.read_csv('ksrtc_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

417

In [73]:
import pandas as pd
from sqlalchemy import create_engine



# connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

#giving the data into csv file

data = pd.read_csv('ktcl_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

312

In [75]:
import pandas as pd
from sqlalchemy import create_engine



# connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"


# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into csv file
data = pd.read_csv('nbstc_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

101

In [76]:
import pandas as pd
from sqlalchemy import create_engine



# connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into csv file

data = pd.read_csv('pepsu_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

761

In [77]:
import pandas as pd
from sqlalchemy import create_engine



# connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into csv file
data = pd.read_csv('rsrtc_bus_details.csv')

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

771

In [78]:
import pandas as pd
from sqlalchemy import create_engine



# Replace with your connection details
host="localhost"
port="5432"
database="homedb"
user="postgres"
password="mukisam290"

# Create the connection string (URL format) -> postgres
engine_string = f"postgresql://{user}:{password}@{host}:{port}/{database}"


# Create the SQLAlchemy engine
engine = create_engine(engine_string)

# giving the data into csv file

data = pd.read_csv("upsrtc_bus_details.csv")

# Table name where you want to push the data
table_name = "bus_details"

# Push the DataFrame to the PostgreSQL table
data.to_sql(table_name, engine,if_exists='append', index=False)  #['fail', 'replace', 'append']

679